package com.example.util;

import freemarker.template.TemplateException;

import java.io.IOException;
import java.sql.SQLException;

/**
 * @author zhagsaiqiang
 * @date 2018/9/30 15:24
 */
public class AutoGenerationDemo {
    public static void main(String[] args) throws ClassNotFoundException, SQLException, IOException, TemplateException {
        //数据库地址
        String url = "jdbc:mysql://127.0.0.1:3306/jeesite";
        //用户名
        String name = "root";
        //密码
        String passWord = "root";
        //驱动
        String driver = "com.mysql.jdbc.Driver";
        //表名
        String tableName = "js_sys_job";
        //模板路径
        String templateDir = "D:\\template";
        //生成文件路径
        String autoGeneratedFile = "D:\\template";
        //实例化
        AutoGenerationJavaCode autoGenerationJavaCode = new AutoGenerationJavaCode(url, name, passWord, driver,
                tableName,autoGeneratedFile,templateDir);

        //调用生成java代码方法
        autoGenerationJavaCode.autoGenerationJavaCode();
    }
}
